baseURL = "https://shut-up-and-code.github.io"
languageCode = "en-us"
title = "shup up and code"
theme = "PaperMod"
disqusShortname = "shut-up-and-code"

[params]
description = "Software development guides by an introvert"
ShowPostNavLinks = true
ShowBreadCrumbs = true

[taxonomies]
tag = "tags"
